//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyBill
    {
        public long MonthlyBillId { get; set; }
        public Nullable<long> RenterId { get; set; }
        public string MonthOfBill { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> CurrentMonthUnit { get; set; }
        public Nullable<decimal> PreviousMonthUnit { get; set; }
        public Nullable<decimal> UnitUsed { get; set; }
        public Nullable<decimal> BillPerUnit { get; set; }
        public Nullable<decimal> ElectricityBill { get; set; }
        public Nullable<decimal> GasBill { get; set; }
        public Nullable<decimal> WaterBill { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
        public Nullable<decimal> OthersBill { get; set; }
        public string PaymentStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
